/**
 * Builds the project's icon set from the installed Iconify collections.
 *
 * Replaces @nuxt/icon, which registered a Nitro server handler that emitted
 * `createRequire(globalThis._importMeta_.url)`. ESM hoisting runs that chunk
 * before the entry assigns `_importMeta_`, so the placeholder
 * "file:///_entry.js" reached createRequire and the server threw on boot.
 * The handler is added unconditionally, so no option could switch it off.
 *
 * The output is committed, so nothing is fetched or generated at build time.
 * Re-run with `npm run icons` after changing ICONS below.
 */
import { createRequire } from "node:module";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const require = createRequire(import.meta.url);

/** Every icon the site uses. Keep sorted within each group. */
const ICONS = [
  // Tech and brand logos
  "simple-icons:bootstrap",
  "simple-icons:css",
  "simple-icons:git",
  "simple-icons:github",
  "simple-icons:html5",
  "simple-icons:javascript",
  "simple-icons:linkedin",
  "simple-icons:nuxtdotjs",
  "simple-icons:pinia",
  "simple-icons:playstation",
  "simple-icons:sass",
  "simple-icons:tailwindcss",
  "simple-icons:telegram",
  "simple-icons:typescript",
  "simple-icons:vite",
  "simple-icons:vuedotjs",
  // Interface
  "lucide:arrow-up-right",
  "lucide:briefcase",
  "lucide:camera",
  "lucide:ellipsis",
  "lucide:gamepad-2",
  "lucide:house",
  "lucide:map-pin",
  "lucide:network",
  "lucide:search",
  "lucide:settings",
  "lucide:sparkles",
  "lucide:trophy",
  "lucide:user",
  "lucide:webhook",
];

const collections = new Map();

function loadCollection(prefix) {
  if (!collections.has(prefix)) {
    collections.set(prefix, require(`@iconify-json/${prefix}/icons.json`));
  }
  return collections.get(prefix);
}

/** Resolves aliases so `lucide:home` style names keep working. */
function resolveIcon(collection, name) {
  const seen = new Set();
  let current = name;

  while (current && !seen.has(current)) {
    seen.add(current);
    if (collection.icons?.[current]) return collection.icons[current];
    current = collection.aliases?.[current]?.parent;
  }
  return null;
}

const entries = [];
const missing = [];

for (const full of ICONS) {
  const [prefix, name] = full.split(":");
  const collection = loadCollection(prefix);
  const icon = resolveIcon(collection, name);

  if (!icon) {
    missing.push(full);
    continue;
  }

  entries.push([
    full,
    {
      body: icon.body,
      width: icon.width ?? collection.width ?? 24,
      height: icon.height ?? collection.height ?? 24,
    },
  ]);
}

if (missing.length) {
  console.error(`[icons] missing from the installed collections: ${missing.join(", ")}`);
  process.exit(1);
}

const file = `/**
 * GENERATED by scripts/generate-icons.mjs - do not edit by hand.
 * Add a name to ICONS in that script and run \`npm run icons\`.
 */
export const icons = ${JSON.stringify(Object.fromEntries(entries), null, 2)};
`;

await writeFile(join(process.cwd(), "data", "icons.js"), file);
console.log(`[icons] wrote ${entries.length} icons to data/icons.js`);
